---
name: Checks

on: [push]

jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run the tests
        run: npm run test

      - name: Build
        run: npm run build
